### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by harish372** [sakshamhere/Automated-Attendance-System-By-Real-Time-Face-Reccognition#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\haris\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "app.py", line 241, in update_in_data_sheet
    wb = load_workbook(f'../data/excel/{year}_{semester.get()}sem_IT{section.get()}.xlsx')
  File "C:\stud\lib\site-packages\openpyxl\reader\excel.py", line 313, in load_workbook
    data_only, keep_links)
  File "C:\stud\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "C:\stud\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "C:\Users\haris\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '../data/excel/fourth_year_sem_ITIT-01.xlsx'

**Comment by sakshamhere** [comment]
you need to place the path properly in code and it works fine, make sure you are putting it according to your directory structure.
